### ISSUE TITLE
Fresh Instalaltion can not find configuration

### ISSUE THREAD

**Issue by xtruthx** [graylog-labs/graylog-vscode-extension#24]
i have a new vscode instalaltion on a windows desktop with the latest version of the plugin. I have also set the settings as described.

I always got:
"Cannot read properties of undefined (reading 'serverUrl')"

When i try to fetch the rules.

**Comment by BlueTeamNinja** [comment]
Yikes!   Our ability to support this is really limited right now but can you paste in the output from the debug console, you have to enable the extensions part.  I can't remember how off the top of my head, but it's where the errors are so we can take a look.

**Comment by xtruthx** [comment]
yeah sorry forgott that. You are right:
```
2023-11-02 13:17:55.176 [error] TypeError: Cannot read properties of undefined (reading 'serverUrl')
	at ConnectionPart.refreshWorkspace (c:\Users\c90156\.vscode\extensions\grayloglabs.graylog-rules-manager-0.1.2\out\graylog.js:209:82)
	at async c:\Users\c90156\.vscode\extensions\grayloglabs.graylog-rules-manager-0.1.2\out\extension.js:16:9
	at async i.h (c:\Users\c90156\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:125:139661) graylog.RefreshWorkSpace {"value":"GraylogLabs.graylog-rules-manager","_lower":"grayloglabs.graylog-rules-manager"}
```

**Comment by xtruthx** [comment]
Question: Where ist the File graylogSettings.json stored?

**Comment by BlueTeamNinja** [comment]
It shouldn't be stored on disk at all but using the internal vscode provider (it has an access key in it).  You can access it from the command pallet or the gear icon in the extension.

Typically, that error comes from not having `http:` in front of your serverURL.  It needs the whole prefix: 

![image](https://github.com/graylog-labs/graylog-vscode-extension/assets/1891183/2f79d61f-d775-471b-b4b1-ea1dc23a7709)

**Comment by xtruthx** [comment]
```{
  "graylogSettings": [
    {
      "serverUrl": "https://10.10.10.10:9000",
      "token": "q6u39jscfldbmnaba30v2g757djglhqgu9cvmna07i2gtdfp0ha",
      "name": "lab"
    }
  ]
}
```
This my `graylogSetting.json`

**Comment by BlueTeamNinja** [comment]
Do you still have the same error?  Last confirmation that your API is available on that address?  It's HTTPS not http and you can connect to that address from your workstation?

We are going to do some bug fixes and updates on this in the next couple of weeks.

**Comment by xtruthx** [comment]
Yes it is https and i got access from my workstation to the graylog api of that graylog instance.

**Comment by BlueTeamNinja** [comment]
Ok.  The error may still display - but if you update the extension, it should now work! 
Remember - once you have added a server, to 'Choose Active server' (CTRL + Shift + P) 

Also, now has a live Grok / regex debugger!
