### ISSUE TITLE
Cannot read properties of undefined (reading 'serverUrl')

### ISSUE THREAD

**Issue by rogermartensson** [graylog-labs/graylog-vscode-extension#26]
I just found this interesting plugin and would like to try it out.

But... I can't get it to work. 
I followed you're instructions and added the tokens and server information but when I try to see something in the Package Explorer/ Graylog I got the error message:
``´Cannot read properties of undefined (reading 'serverUrl')```

Can't see how I could've done anything wrong when adding the servers.

**Comment by BlueTeamNinja** [comment]
Usually this is blamed on a trailing slash or not having the https://

We've seen a couple instances of this but haven't had much time to get it figured out.  If you can send us the extension console log from vscode we can work on it.

**Comment by rogermartensson** [comment]
Sorry for being late. Anyway. this is a copy of the only line that appears in the log för Extension Host.

Can also say that I run VScode on Windows 11.
```
2024-03-07 10:21:49.909 [error] TypeError: Cannot read properties of undefined (reading 'serverUrl')
	at ConnectionPart.refreshWorkspace (c:\Users\username\.vscode\extensions\grayloglabs.graylog-rules-manager-0.1.3\out\graylog.js:198:82)
	at async c:\Users\username\.vscode\extensions\grayloglabs.graylog-rules-manager-0.1.3\out\extension.js:17:9
	at async l.h (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:184946) graylog.RefreshWorkSpace {"value":"GraylogLabs.graylog-rules-manager","_lower":"grayloglabs.graylog-rules-manager"}
```
